Hungry jay
dev-floor/kotlin-racingcar pull request #1
Opened 2020-12-24 02:50 UTC by hungry-jay

2020-12-27 07:52 UTC, lxxjn0 requested changes
제가 아는 범위만큼 피드백 남겨봤습니다 😄

2020-12-27 07:52 UTC, lxxjn0 commented on java-kotlin-js-convention.xml
> +<code_scheme name="java-kotlin-js-convention" version="173">
해당 파일은 IntelliJ에 적용만 하고 따로 저장해서 관리하지 않아도 될 것 같아요!!

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/RacingCarApplication.kt
> +    val resultView = ResultView()
view 같은 경우에는 따로 인스턴스로 관리하지 않고 최상위 함수로 사용해도 괜찮지 않을까요?

유틸리티 클래스에 더 가깝다고 느껴져서 인스턴스로 관리하지 않아도 될 것 같아요!!

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/RacingCarApplication.kt
> +    cars.carList = carNames!!.map { name -> Car(name) }
이 부분은 setter로 프로퍼티를 초기화하는데 그 방법보다는 생성자를 활용하는 편이 더 낫지 않을까요?

또는 유연하게 타입을 받을 수 있는 정적 팩토리 메서드를 만드는 것도 좋을 것 같아요 :)

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/Car.kt
> +class Car(val name: String = "", var position: Position = Position("")) {
position 프로퍼티에 대한 default arguments를 Position("")으로 주고 있어요. Position에도 default argument로 "" 빈 문자열을 받도록 구현하면 이 코드가 더 깔끔해 질 것 같아요!!

```kotlin
class Position(val position: String = "")

class Car(val name: String = "", var position: Position = Position())
```

이렇게 작성해도 같은 기능을 할 것 같아요!!

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/Car.kt
> +    fun move(randomValue: Int) {
이 부분은 아까 보내드린 피드백에서 있는 내용을 참조했어요.

Car 인스턴스의 경우 이동할 때 들어오는 number가 랜덤인지 아닌지는 중요하지 않고 단순히 조건에 만족하는 번호인지가 중요한 것 같아요. 그래서 이 매개변수의 명명에 대해서는 randomValue말고 value로 써도 괜찮을 것 같아요. 아니면 숫자라는 것을 알 수 있도록 number도 괜찮을 것 같아요~

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/Position.kt
> +    fun accelerate() = Position("$position-")
Position이 본인의 위치를 숫자가 아니라 `-` 문자로 가지고 있어요. 이 부분은 숫자의 위치가 1인지 2인지를 표현하기 위한 문자에 가깝다고 생각해요.

만약 위치를 `-`이 아니라 🏎 라는 이모티콘으로 한다면? 그럼 view에서 출력하는 로직에 대해서만 변경을 하면 되는걸 Position이라는 도메인 로직에 변경을 가해야 해요.

`-`으로 위치를 표시한다는 요구사항은 view의 로직이라는 생각이 들어서 숫자로 위치 값을 가지고 있고 출력할 때 숫자의 크기만큼 `-`을 보여주는 것이 좋을 것 같아요!!

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +class Cars(var carList: List<Car> = emptyList()) {
자동차들을 carList라는 프로퍼티에 관리하는 것 같아요. 그런데 보통 불용어는 명명에 사용하지 않는 것이 좋다고 하더라고요(자바 컨벤션에서는 사용하지 말라고 학습했는데 코틀린에서는 어떨지 모르겠어요)

자동차들을 담고있는 자료구조가 List인데 만약 MutableList, Set 등으로 바뀐다면 프로퍼티의 이름을 바꿔야 할까요? 특정한 자료구조를 명명에 사용하게 되면 해당 프로퍼티의 자료구조가 변경될 때마다 명명을 수정해야 하는 번거로움이 발생할 수 있어요. 그래서 최대한 불용어를 명명에 사용하지 말라고 알고 있어요. 이 부분은 코틀린 컨벤션을 참고해봐도 좋을 것 같아요 👍

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    fun getWinnerList():
이 함수의 경우 프로퍼티로 관리하는 것은 어떨까요? 자동차들 중에 승자는 어떻게 보면 속성에 가까운 느낌이 들어서 추천드려보겠습니다

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    fun moveCars() = carList.forEach() { it.move(Random().getRandomValue()) }
해당 함수에 대한 로직을 테스트하기 쉽도록 하기 위해서 전략 패턴을 한 번 참고해보는 것도 좋을 것 같아요.

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/Random.kt
> +class Random {
이 클래스가 java.util에서 기본적으로 제공하는 Random 클래스와 명명이 같아서 사용이 헛갈릴 것 같아요. 좀 더 구체적인 이름을 정해 보는 것도 좋을 것 같아요!!

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/view/InputView.kt
> +class InputView {
이 부분은 이전에 말씀드린 것처럼 인스턴스가 아니라 최상위 함수로 관리하면 좋을 것 같아요 👍

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/view/InputView.kt
> +        return validateCarNames(readLine()?.split(","))
콤마도 상수로 뽑아보면 좋을 것 같아요 :)

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/view/InputView.kt
> +        names!!.forEach { require(it.length <= 5) { "자동차 이름은 5자 이하만 가능합니다." } }
이름을 감싸는 객체를 만들어서 유효성 검증에 대한 위치를 해당 객체에 위임하는 구조는 어떨까요?

그리고 5와 같은 매직 넘버도 상수로 관리하면 좋을 것 같아요. 그렇다면 5라는 숫자를 봤을 때 이게 무엇을 의미하는지 더 쉽게 알아 볼 수 있어요

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/view/InputView.kt
> +        println("\n" + "시도할 횟수는 몇 회인가요?")
이 문자열도 `"\n시도할..."`로 합쳐서 해도 될 것 같아요!!!

2020-12-27 07:52 UTC, lxxjn0 commented on src/main/kotlin/racingcar/view/ResultView.kt
> +        cars.carList.forEach { println(it.name + " : " + it.position.position) }
이 부분은 문자열 템플릿을 활용하면 더 깔끔하게 작성할 수 있을 것 같아요!!

2020-12-27 07:52 UTC, lxxjn0 commented on src/test/kotlin/racingcar/Car.kt
> +class Car {
테스트 클래스의 경우 주로 CarTest와 같이 명명을 가져가는 것 같아요!!

2021-01-06 07:15 UTC, hungry-jay commented on java-kotlin-js-convention.xml
> +<code_scheme name="java-kotlin-js-convention" version="173">
제외시켰음!!

2021-01-06 07:18 UTC, hungry-jay commented on src/main/kotlin/racingcar/RacingCarApplication.kt
> +    val resultView = ResultView()
최상위 함수! 클래스 보다는 그쪽이 더 잘 어울릴 것 같다 굿

2021-01-06 07:19 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Car.kt
> +class Car(val name: String = "", var position: Position = Position("")) {
더 깔끔하게 변경 !

2021-01-06 07:20 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Car.kt
> +    fun move(randomValue: Int) {
number로 변경하는게 좋을거같다 !!

2021-01-06 07:37 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Car.kt
> +class Car(val name: String = "", var position: Position = Position("")) {
++ position을 Int로 변경하면서 `class Position(val position: Int = 0)` 이와같이 변경했음

2021-01-06 07:38 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Position.kt
> +    fun accelerate() = Position("$position-")
숫자로 변경하고 view에서 해당 숫자만큼 --를 출력하는거로 바꾸는게 좋겠다!
또한 이에 따라 test코드도 같이 변경예정

2021-01-06 07:51 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Cars.kt
> +class Cars(var carList: List<Car> = emptyList()) {
carList -> cars로 변경하는게 좋을거같다 불용어를 사용하지 않는거 좋은거배워감 ㅠ

2021-01-06 07:57 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Random.kt
> +class Random {
RandomNumber class로 변경했어!

2021-01-06 07:59 UTC, hungry-jay commented on src/main/kotlin/racingcar/view/InputView.kt
> +class InputView {
굿

2021-01-06 08:04 UTC, hungry-jay commented on src/main/kotlin/racingcar/view/InputView.kt
> +        return validateCarNames(readLine()?.split(","))
바로 아래 코멘트도 그렇고 숫자, 문자같은건 상수로 관리하는게 좋긴하겠다 !

2021-01-06 08:04 UTC, hungry-jay commented on src/main/kotlin/racingcar/view/InputView.kt
> +        names!!.forEach { require(it.length <= 5) { "자동차 이름은 5자 이하만 가능합니다." } }
굿굿

2021-01-06 08:05 UTC, hungry-jay commented on src/main/kotlin/racingcar/view/InputView.kt
> +        println("\n" + "시도할 횟수는 몇 회인가요?")
+를 사용하는게 더 깔끔할거같았는데 변수 넣는경우에도 $를 사용하다보니 이게 더 깔끔한 느낌이네!!

2021-01-06 08:07 UTC, hungry-jay commented on src/main/kotlin/racingcar/view/ResultView.kt
> +        cars.carList.forEach { println(it.name + " : " + it.position.position) }
아 이걸 문자열 템플릿이라고 부르는구나..ㅋㅋㅋㅋ

2021-01-06 08:07 UTC, hungry-jay commented on src/test/kotlin/racingcar/Car.kt
> +class Car {
굿 !

2021-01-06 08:38 UTC, hungry-jay commented on src/main/kotlin/racingcar/view/InputView.kt
> +        names!!.forEach { require(it.length <= 5) { "자동차 이름은 5자 이하만 가능합니다." } }
유효성 검증의 경우 Car 내부에 init {}에서 검사하도록 했어!

2021-01-07 01:51 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    fun getWinnerList():
프로퍼티로 변경했고 그 과정에서 winner 한명만 구하는 method 또한 없앴음 !

2021-01-07 01:52 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    fun getWinnerList():
추가) method가 하나 없어지면서 테스트 코드도 하나 축소

2021-01-07 02:15 UTC, hungry-jay commented on src/main/kotlin/racingcar/RacingCarApplication.kt
> +    cars.carList = carNames!!.map { name -> Car(name) }
> 이 부분은 setter로 프로퍼티를 초기화하는데 그 방법보다는 생성자를 활용하는 편이 더 낫지 않을까요?

Cars 생성자를 통해 초기화하는 방법으로 고침

2021-01-07 02:49 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Cars.kt
> +    fun moveCars() = carList.forEach() { it.move(Random().getRandomValue()) }
moveCars에서 getRandomValue를 하는것이 아니라 moveCars를 호출하는 부분에서 random value를 전달하는 방식으로 하면 되나 !?

2021-01-09 12:55 UTC, lxxjn0 commented on src/main/kotlin/racingcar/view/InputView.kt
> +        println("\n" + "시도할 횟수는 몇 회인가요?")
위 코드에서 +는 결국 문자열을 더하는 연산 작업이잖아? 그래서 불필요한 연산을 굳이 만들 필요가 없다고 생각했어 :)

2021-01-09 13:33 UTC, lxxjn0 requested changes
일단 추가적으로 테스트랑 보이는 부분에 대해서 리뷰 몇 가지 만들어놨어.

그리고 전체적인 로직을 보면 잘못된 입력에 대한 예외 처리가 없는 것 같아.
만약 시도 횟수가 0보다 작은 숫자가 입력되면 재 입력을 요구하는 것처럼?

프로그램 적인 부분에서 이런 예외를 처리해주면 좀 더 사용하기 좋은 프로그램이 될 것 같아. 시간 여유가 된다면 이런 부분도 추가하면 좋을 듯?

전반적인 코드는 다 좋아진 것 같어!!! 💯 💯 💯

2021-01-09 13:33 UTC, lxxjn0 commented on src/main/kotlin/racingcar/RacingCarApplication.kt
> +    val cars = Cars(getCarNames().map { name -> Car(name) }.toList())
```suggestion
    val carNames = getCarNames().map { name -> Car(name) }
            .toList()
    val cars = Cars(carNames)
```

이런 식으로 변경하면 어떨까?
Cars 생성자가 어떠한 인자를 받는 지 좀 더 명확히 드러낼 수 있을 것 같아.

그리고 추가적으로 저렇게 Chaining Method의 경우 `.` 를 기준으로 개행을 하면 더 가독성을 높일 수도 있어 👍

2021-01-09 13:33 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/Car.kt
> +        const val NAME_THRESHOLD = 5
상수의 이름이 너무 추상적인 것 같아. 단순히 threshold라는 단어를 쓰기보단 해당 상수가 로직 내에서 어떠한 역할을 하는지 상수명으로 드러내면 코드를 읽을 때 좀 더 명확하지 않을까?

이름의 최대 길이니까 `NAME_MAX_LENGTH` 같은 식으로? `MOVE_THRESHOLD` 이름은 괜찮아 보이기도 하고, 마땅한 이름은 안떠오르네 😅

2021-01-09 13:33 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/Cars.kt
> +class Cars(var cars: List<Car>) {
프로그램의 로직 상 cars 변수에 할당된 `List<Car>`는 재할당이 될 상황이 없지 않을까?
그럼 mutable 변수말고 immutable로 초기화하는게 더 좋을 것 같어. var 말고 val로!

2021-01-09 13:33 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/Cars.kt
>          }
```suggestion
        get() = cars.filter { it -> it.position.position == cars.maxByOrNull { it.position.position }!!.position.position }
                .map { it.name }
                .toList()
```

또는

```suggestion
        get() {
            val winningPosition = cars.maxByOrNull { it.position.position }!!.position.position

            return cars.filter { it -> it.position.position == winningPosition }
                .map { it.name }
                .toList()
        }
```

만약 함수를 전부 안으로 넣을 생각이면 expression 형식이 더 보기 좋을 것 같고, 만약 그렇지 않으면 따로 상수를 뽑는게 코드를 보기 더 편할 것 같아.

상수를 뽑는 것이 가지는 장점은 해당 반환값이 어떠한 역할을 하는지 좀 더 명확히 드러낼 수 있다거든.
그래서 단순히 코드 줄수를 줄이기 위해 코드 안에 다 넣기보단 이런 분리가 좀 더 코드가 잘 읽힐 수 있게 해주는 것 같아.

그리고 `!!` 연산자가 null이 반환될 경우 NPE를 던져준다고 알고 있는데 null이 반환되는 많은 로직들을 이런 방식으로 처리했더라고.

Kotlin이 Java에 비해 가지는 장점이 null 처리잖아. 그래서 null이 반환되는 로직에서 좀 더 명시적으로 처리를 해주면 좋을 것 같은데 이런 코드의 형식이면 Java 코드를 짜는 방식과 크게 다르지 않나?라는 생각이 들었어

이건 나도 확실한 부분이 아니라서 한번 생각해보는 것도 좋을 것 같아!
(근데 글을 쓰다보니 null이 반환될 수 있음을 알고, 그 상황에 대해서 개발자가 명시적으로 NPE를 던지는 거니까 괜찮은거 같기도?? ㅋㅋㅋ)

2021-01-09 13:33 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/Position.kt
>  }
Position 인스턴스가 값을 표현하는 그 이상, 이하가 아니라고 생각이 드는데 Data Class도 한번 생각해볼 만한거 같아!
그렇다면 코드가

```suggestion
data class Position(val position: Int = 0) {
    fun accelerate() = this.copy(position + 1) // 이 코드는 에러가 안나는지는 확실히 모르겠다. 지금 그냥 Github에서 바로 쓰고 있어서 ㅋㅋㅋ
}
```

2021-01-09 13:33 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/RandomNumber.kt
> +        const val RANDOM = 10
상수 이름이 너무 추상적인것 같아! 

랜덤한 값으로 생성될 수 있는 최대 범위라면 `RANDOM_UPPER_BOUND` 정도의 이름이라도 지어주면 변수가 뭘 의미하는지 좀 더 잘 파악할 수 있지 않을까?

2021-01-09 13:33 UTC, lxxjn0 commented on src/test/kotlin/racingcar/CarsTest.kt
> +    fun `Each car should move properly`() {
이 테스트는 Cars 클래스의 테스트가 아닌 것 같은데?
Cars 인스턴스의 `moveCars()` 메서드에 대한 테스트가 아니라 결국 각각의 Car 인스턴스의 move 메서드 대한 테스트로 보여지네

이거 내가 쓴 글인데 이거 한 번 참고해서 Cars 클래스를 수정해보는 것도 좋을 것 같어
> [인터페이스를 분리하여 테스트하기 좋은 메서드로 만들기](https://woowacourse.github.io/javable/post/2020-05-17-appropriate_method_for_test_by_interface/) - 이건 우테코 블로그
> [인터페이스를 분리하여 테스트하기 좋은 메서드로 만들기](https://velog.io/@lxxjn0/%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4%EB%A5%BC-%EB%B6%84%EB%A6%AC%ED%95%98%EC%97%AC-%ED%85%8C%EC%8A%A4%ED%8A%B8%ED%95%98%EA%B8%B0-%EC%A2%8B%EC%9D%80-%EB%A9%94%EC%84%9C%EB%93%9C%EB%A1%9C-%EB%A7%8C%EB%93%A4%EA%B8%B0) - 이건 내 개인 블로그 ㅋㅋㅋ

2021-01-09 13:33 UTC, lxxjn0 commented on src/test/kotlin/racingcar/CarsTest.kt
> +    fun `Each car should move properly`() {
아마 Cars의 구조를 변경하면 자연스럽게 테스트도 가능한 구조가 될 거야

2021-01-09 13:33 UTC, lxxjn0 commented on src/test/kotlin/racingcar/PositionTest.kt
> +        assertThat(Car("carA").position.position + 1).isEqualTo(Car("carB").position.accelerate().position)
이것도 테스트가 조금 이상한 것 같아.
Car 인스턴스를 생성하지 말고 Position 인스턴스를 직접 생성해서 테스트하는게 맞는 것 같아.

이러면 테스트가 Car 인스턴스에 종속되게 돼.
Position의 로직에 대한 테스트만 이뤄져야 하는데 만약 Car 인스턴스의 프로퍼티에서 Position이 빠진다면?
Position 자체의 로직은 여전히 잘 동작하는데 이 테스트는 아예 컴파일 에러가 발생해버려

단위 테스트의 장점은 테스트의 범위를 최소한 해당 클래스에 국한시켜서 로직을 테스트하는 건데 이런 테스트의 경우 다른 클래스에 의존이 생기니까 좋지 않은 테스트라고 생각해.

추가적으로 저 테스트의 경우 전혀 다른 2개의 Car 인스턴스를 비교하고 있어. 
한 대의 자동차가 이동하기 전과 이동한 후의 위치를 비교하는게 좀 더 맞는 것 같어 👍

2021-01-11 09:27 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Car.kt
> +        const val NAME_THRESHOLD = 5
`NAME_MAX_LENGTH` 좋은거 같다. ! 저기서 생각난건데 `NAME_LENGTH_LIMIT` 이런 건 어떨까 ??

2021-01-11 09:30 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Cars.kt
> +class Cars(var cars: List<Car>) {
굿! const > val > var 순으로 lint가 선호할거같고 그렇게 잡아줄줄 알았는데 ㅠ 내가 lint를 잘못쓰고있는건가....

2021-01-11 09:35 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Cars.kt
>          }
(근데 글을 쓰다보니 null이 반환될 수 있음을 알고, 그 상황에 대해서 개발자가 명시적으로 NPE를 던지는 거니까 괜찮은거 같기도?? ㅋㅋㅋ) << - 이 부분에 대해서 어떠한 경우에도 null이 발생하지 않을걸 알기에 일종의 Assertion? 느낌으로 `!!` 를 사용하는거로 알고있었어 나는 ㅋㅋㅋ.. 이부분에 대한 정확한 공부가 필요할거같다 ㅋㅋ

코드 방식은 밑에가 더 잘 읽히는 코드인거같다 ㅎㅎ 변수로 분리하는게 아무래도 좋을 듯

2021-01-11 09:38 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Position.kt
>  }
아.. 데이터 클래스 저번에 너한테 이야기 들은거 기억난다 ㅋㅋㅋ
현재로썬 확장 될 여지가 없기 때문에 data class로 두는게 좋을거같네

2021-01-11 09:48 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/RandomNumber.kt
> +        const val RANDOM = 10
`RANDOM_UPPER_BOUND` 이름 좋다.. ㅋㅋㅋ 유용하게 쓰일듯..

2021-01-11 09:50 UTC, hungry-jay commented on src/main/kotlin/racingcar/RacingCarApplication.kt
> +    val cars = Cars(getCarNames().map { name -> Car(name) }.toList())
요거 또한 밑에서(맞나..?) 언급한 부분처럼 변수로 나누는게 더 가독성있고 의미 있어 보이겠네 ㅎㅎ

2021-01-11 09:52 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Car.kt
> +        const val NAME_THRESHOLD = 5
아근데 다시보니 전자( `NAME_MAX_LENGTH`) 가 훨씬 깔끔해보인다 ㅋㅋ

2021-01-11 09:59 UTC, hungry-jay commented on src/main/kotlin/racingcar/domain/Car.kt
> +        const val NAME_THRESHOLD = 5
`MOVE_THRESHOLD` 얘는 더 적절한게 있을까 고민하다가 찾았는데
https://www.curioustore.com/#!/util/naming
변수명 지어주는 사이트도 있네 ㅋㅋㅋ

2021-01-11 12:01 UTC, lxxjn0 commented on src/main/kotlin/racingcar/domain/Car.kt
> +        const val NAME_THRESHOLD = 5
변수명 지어주는 사이트는 좀 참신하네 ㅋㅋㅋㅋㅋ

2021-01-13 09:43 UTC, hungry-jay commented on src/test/kotlin/racingcar/CarsTest.kt
> +    fun `Each car should move properly`() {
드디어 이해했다 전략패턴 ㅋㅋㅋ 저 글 좋네 !!!

2021-01-13 09:50 UTC, hungry-jay commented on src/test/kotlin/racingcar/PositionTest.kt
> +        assertThat(Car("carA").position.position + 1).isEqualTo(Car("carB").position.accelerate().position)
종속성을 최대한 줄여서(없애서) 테스트를 하는게 맞네 .. 
종속적이지 않은 class를 import하지 않아도 전혀 문제가 발생하지 않도록 테스트 변경했어 !

2021-01-13 09:51 UTC, hungry-jay commented on src/test/kotlin/racingcar/PositionTest.kt
> +        assertThat(Car("carA").position.position + 1).isEqualTo(Car("carB").position.accelerate().position)
`추가적으로 저 테스트의 경우 전혀 다른 2개의 Car 인스턴스를 비교하고 있어.
한 대의 자동차가 이동하기 전과 이동한 후의 위치를 비교하는게 좀 더 맞는 것 같어 +1` 이 부분에 대해서는 position 인스턴스를 통해서 비교하도록 변경했어

2021-03-01 13:36 UTC, lxxjn0 approved these changes
이 미션은 전체적으로 잘 마무리 된 것 같아!! 리뷰 반영한다고 수고했으~~~ 👍

2021-03-01 15:02 UTC, hungry-jay commented
> 이 미션은 전체적으로 잘 마무리 된 것 같아!! 리뷰 반영한다고 수고했으~~~ 👍

굿굿 리뷰 땡큐 ㅎㅎ merge할게!

2021-03-01 15:03 UTC, merged